"""add_global_subjects_and_grade_column

Revision ID: 21eafe64223c
Revises: 
Create Date: 2026-05-13 16:56:01.333041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21eafe64223c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_subjects',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('subjects', sa.Column('grade', sa.String(), nullable=False))
    op.add_column('subjects', sa.Column('template_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'template_id')
    op.drop_column('subjects', 'grade')
    op.drop_table('global_subjects')
    # ### end Alembic commands ###
