"""add_academic_units_to_global_subjects

Revision ID: 4139ac9e0a0d
Revises: 21eafe64223c
Create Date: 2026-05-13 16:12:20.082432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4139ac9e0a0d'
down_revision: Union[str, Sequence[str], None] = '21eafe64223c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_subjects', sa.Column('academic_units', sa.Integer(), nullable=True))
    op.execute("UPDATE global_subjects SET academic_units = 3")
    op.alter_column('global_subjects', 'academic_units', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_subjects', 'academic_units')
    # ### end Alembic commands ###
