"""link subject offerings to class groups

Revision ID: 94e759c3acae
Revises: f51b3f02b78c
Create Date: 2026-05-14 07:46:40.760702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e759c3acae'
down_revision: Union[str, Sequence[str], None] = 'f51b3f02b78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_offerings', sa.Column('class_group_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'subject_offerings', 'class_groups', ['class_group_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_offerings', type_='foreignkey')
    op.drop_column('subject_offerings', 'class_group_id')
    # ### end Alembic commands ###
