"""add assessments_per_unit to subjects

Revision ID: 9a1988aa5ac1
Revises: 94e759c3acae
Create Date: 2026-05-14 20:57:58.973804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1988aa5ac1'
down_revision: Union[str, Sequence[str], None] = '94e759c3acae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add columns as nullable first
    op.add_column('global_subjects', sa.Column('assessments_per_unit', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('assessments_per_unit', sa.Integer(), nullable=True))
    
    # 2. Set default values for existing rows
    op.execute("UPDATE global_subjects SET assessments_per_unit = 3")
    op.execute("UPDATE subjects SET assessments_per_unit = 3")
    
    # 3. Make them NOT NULL
    op.alter_column('global_subjects', 'assessments_per_unit', nullable=False)
    op.alter_column('subjects', 'assessments_per_unit', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'assessments_per_unit')
    op.drop_column('global_subjects', 'assessments_per_unit')
    # ### end Alembic commands ###
