"""add class_group_id to offerings

Revision ID: b155972a6e6f
Revises: c020f6a6abbe
Create Date: 2026-05-14 22:53:58.325947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b155972a6e6f'
down_revision: Union[str, Sequence[str], None] = 'c020f6a6abbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_offerings', sa.Column('class_group_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'subject_offerings', 'class_groups', ['class_group_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_offerings', type_='foreignkey')
    op.drop_column('subject_offerings', 'class_group_id')
    # ### end Alembic commands ###
