"""create grades table

Revision ID: c020f6a6abbe
Revises: 9a1988aa5ac1
Create Date: 2026-05-14 22:48:22.048540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c020f6a6abbe'
down_revision: Union[str, Sequence[str], None] = '9a1988aa5ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('offering_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('assessment_number', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('observations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.uid'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('offering_id', 'student_id', 'unit', 'assessment_number', name='_student_assessment_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    # ### end Alembic commands ###
