"""add regular class concept to class groups

Revision ID: f51b3f02b78c
Revises: 4139ac9e0a0d
Create Date: 2026-05-13 17:39:03.507182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f51b3f02b78c'
down_revision: Union[str, Sequence[str], None] = '4139ac9e0a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add columns as nullable first
    op.add_column('class_groups', sa.Column('period', sa.String(), nullable=True))
    op.add_column('class_groups', sa.Column('is_regular', sa.Boolean(), nullable=True))
    op.add_column('class_groups', sa.Column('level', sa.String(), nullable=True))
    op.add_column('class_groups', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('class_groups', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('class_groups', sa.Column('offering_ids', sa.JSON(), nullable=True))
    op.add_column('class_groups', sa.Column('required_subject_ids', sa.JSON(), nullable=True))
    
    # 2. Fill existing data
    op.execute("UPDATE class_groups SET period = '2024', is_regular = false, offering_ids = '[]', required_subject_ids = '[]'")
    
    # 3. Rename or migration base_subject_ids to offering_ids if needed
    # Actually autogenerate detected add/drop, let's migrate data if it existed
    op.execute("UPDATE class_groups SET offering_ids = base_subject_ids WHERE base_subject_ids IS NOT NULL")
    
    # 4. Set nullable=False for required fields
    op.alter_column('class_groups', 'period', nullable=False)
    op.drop_column('class_groups', 'base_subject_ids')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_groups', sa.Column('base_subject_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('class_groups', 'required_subject_ids')
    op.drop_column('class_groups', 'offering_ids')
    op.drop_column('class_groups', 'notes')
    op.drop_column('class_groups', 'grade')
    op.drop_column('class_groups', 'level')
    op.drop_column('class_groups', 'is_regular')
    op.drop_column('class_groups', 'period')
    # ### end Alembic commands ###
